project_id = "lvtzhdmmichasbwsszfk"

[functions.accept-invite-existing-user]
verify_jwt = false

[functions.accept-invite]
verify_jwt = false

[functions.migrate-movements-to-financeiro]
verify_jwt = true