project_id = "lvtzhdmmichasbwsszfk"

[functions.accept-invite-existing-user]
verify_jwt = false

[functions.accept-invite]
verify_jwt = false

[functions.migrate-movements-to-financeiro]
verify_jwt = true

[functions.calcular-previsoes]
verify_jwt = true

[functions.enviar-alertas-estoque]
verify_jwt = true

[functions.gerar-relatorio-semanal]
verify_jwt = false

[functions.gerar-relatorio-diario]
verify_jwt = false

[functions.gerar-analise-ia]
verify_jwt = true

[functions.enviar-relatorio-semanal-ia]
verify_jwt = false